/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    products: Product;
    'product-categories': ProductCategory;
    leads: Lead;
    posts: Post;
    policies: Policy;
    stores: Store;
    certifications: Certification;
    media: Media;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    products: ProductsSelect<false> | ProductsSelect<true>;
    'product-categories': ProductCategoriesSelect<false> | ProductCategoriesSelect<true>;
    leads: LeadsSelect<false> | LeadsSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    policies: PoliciesSelect<false> | PoliciesSelect<true>;
    stores: StoresSelect<false> | StoresSelect<true>;
    certifications: CertificationsSelect<false> | CertificationsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  name: string;
  headline?: string | null;
  /**
   * 2–4 câu, hiện ở thẻ sản phẩm và mô tả SEO.
   */
  summary: string;
  highlights?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Ảnh đầu tiên là ảnh đại diện.
   */
  images?: (number | Media)[] | null;
  specs?: {
    /**
     * Để trống với món ăn tại quán.
     */
    price?: number | null;
    /**
     * Vd: quả, túi, kg
     */
    priceUnit?: string | null;
    netWeight?: string | null;
    shelfLife?: string | null;
    storage?: string | null;
    usage?: string | null;
  };
  seo?: {
    /**
     * Để trống sẽ dùng tên sản phẩm.
     */
    title?: string | null;
    /**
     * Để trống sẽ dùng tóm tắt.
     */
    description?: string | null;
  };
  /**
   * Để trống sẽ tự tạo từ tên, vd: nem-ngua
   */
  slug: string;
  category: number | ProductCategory;
  featured?: boolean | null;
  /**
   * Chỉ bật cho sản phẩm thuộc phạm vi chứng nhận (hiện tại: nem lợn, nem ngựa).
   */
  isoBadge?: boolean | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Mô tả ngắn nội dung ảnh — tốt cho SEO & người khiếm thị.
   */
  alt: string;
  caption?: string | null;
  prefix?: string | null;
  _objectKey?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-categories".
 */
export interface ProductCategory {
  id: number;
  name: string;
  /**
   * Để trống sẽ tự tạo từ tên, vd: nem-ngua
   */
  slug: string;
  /**
   * Vd: Phục vụ tại hệ thống cơ sở nhượng quyền
   */
  note?: string | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Thông tin khách gửi từ các form: đặt hàng, đăng ký nhượng quyền, liên hệ.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads".
 */
export interface Lead {
  id: number;
  type: 'order' | 'franchise' | 'contact';
  status: 'new' | 'contacted' | 'won' | 'lost';
  name: string;
  phone: string;
  email?: string | null;
  province?: string | null;
  message?: string | null;
  franchiseInfo?: {
    hasPremises?: ('yes' | 'no') | null;
    budget?: string | null;
  };
  orderInfo?: {
    items?:
      | {
          product?: (number | null) | Product;
          quantity?: number | null;
          id?: string | null;
        }[]
      | null;
    address?: string | null;
  };
  assignee?: (number | null) | User;
  internalNote?: string | null;
  sourcePage?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  /**
   * Admin: toàn quyền. Editor: sửa nội dung & xử lý khách hàng, không quản lý tài khoản / cài đặt.
   */
  role?: ('admin' | 'editor') | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  /**
   * 1–3 câu, hiện ở thẻ bài viết và mô tả SEO.
   */
  excerpt: string;
  cover?: (number | null) | Media;
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  seo?: {
    /**
     * Để trống sẽ dùng tiêu đề bài.
     */
    title?: string | null;
    /**
     * Để trống sẽ dùng tóm tắt.
     */
    description?: string | null;
  };
  /**
   * Để trống sẽ tự tạo từ tên, vd: nem-ngua
   */
  slug: string;
  category: 'tin-tuc' | 'khai-truong' | 'hoat-dong';
  publishedAt: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Vận chuyển, thanh toán, đổi trả, bảo mật… — hiện ở chân trang, đường dẫn /chinh-sach/<slug>.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "policies".
 */
export interface Policy {
  id: number;
  title: string;
  /**
   * 1–2 câu dưới tiêu đề, dùng làm mô tả SEO.
   */
  summary: string;
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Để trống sẽ tự tạo từ tên, vd: nem-ngua
   */
  slug: string;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Danh sách cơ sở hiển thị ở trang Hệ thống cơ sở. Chưa có cơ sở nào → trang chỉ hiện số liệu & ảnh khai trương.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stores".
 */
export interface Store {
  id: number;
  name: string;
  province:
    | 'Hà Nội'
    | 'TP. Hồ Chí Minh'
    | 'Hải Phòng'
    | 'Đà Nẵng'
    | 'Cần Thơ'
    | 'Huế'
    | 'An Giang'
    | 'Bắc Ninh'
    | 'Cà Mau'
    | 'Cao Bằng'
    | 'Đắk Lắk'
    | 'Điện Biên'
    | 'Đồng Nai'
    | 'Đồng Tháp'
    | 'Gia Lai'
    | 'Hà Tĩnh'
    | 'Hưng Yên'
    | 'Khánh Hòa'
    | 'Lai Châu'
    | 'Lâm Đồng'
    | 'Lạng Sơn'
    | 'Lào Cai'
    | 'Nghệ An'
    | 'Ninh Bình'
    | 'Phú Thọ'
    | 'Quảng Ngãi'
    | 'Quảng Ninh'
    | 'Quảng Trị'
    | 'Sơn La'
    | 'Tây Ninh'
    | 'Thái Nguyên'
    | 'Thanh Hóa'
    | 'Tuyên Quang'
    | 'Vĩnh Long';
  phone?: string | null;
  address: string;
  /**
   * Dán link chia sẻ vị trí từ Google Maps (để khách bấm Chỉ đường).
   */
  mapUrl?: string | null;
  image?: (number | null) | Media;
  openedAt?: string | null;
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Chứng nhận hiện trên website (khối "Chứng nhận và cam kết chất lượng"). Admin báo trước 6 tháng khi sắp hết hạn.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "certifications".
 */
export interface Certification {
  id: number;
  /**
   * Vd: ISO 22000:2018
   */
  standard: string;
  /**
   * Vd: Hệ thống Quản lý An toàn Thực phẩm
   */
  name: string;
  number: string;
  issuer: string;
  holder: string;
  /**
   * Vd: Quyết định số 274/QĐ-WCERT ngày 24/6/2025
   */
  decision?: string | null;
  /**
   * Chỉ gắn huy hiệu chứng nhận cho sản phẩm thuộc phạm vi này.
   */
  scope: string;
  location?: string | null;
  issuedAt: string;
  expiresAt: string;
  /**
   * Vd: Định kỳ 12 tháng/lần
   */
  surveillance?: string | null;
  /**
   * Ảnh giấy chứng nhận, quyết định… — hiện dạng thẻ giấy, bấm để phóng to.
   */
  documents?:
    | {
        title: string;
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  active?: boolean | null;
  /**
   * Chứng nhận có thứ tự nhỏ nhất hiện ở website.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'product-categories';
        value: number | ProductCategory;
      } | null)
    | ({
        relationTo: 'leads';
        value: number | Lead;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'policies';
        value: number | Policy;
      } | null)
    | ({
        relationTo: 'stores';
        value: number | Store;
      } | null)
    | ({
        relationTo: 'certifications';
        value: number | Certification;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  name?: T;
  headline?: T;
  summary?: T;
  highlights?:
    | T
    | {
        text?: T;
        id?: T;
      };
  body?: T;
  images?: T;
  specs?:
    | T
    | {
        price?: T;
        priceUnit?: T;
        netWeight?: T;
        shelfLife?: T;
        storage?: T;
        usage?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
      };
  slug?: T;
  category?: T;
  featured?: T;
  isoBadge?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-categories_select".
 */
export interface ProductCategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  note?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads_select".
 */
export interface LeadsSelect<T extends boolean = true> {
  type?: T;
  status?: T;
  name?: T;
  phone?: T;
  email?: T;
  province?: T;
  message?: T;
  franchiseInfo?:
    | T
    | {
        hasPremises?: T;
        budget?: T;
      };
  orderInfo?:
    | T
    | {
        items?:
          | T
          | {
              product?: T;
              quantity?: T;
              id?: T;
            };
        address?: T;
      };
  assignee?: T;
  internalNote?: T;
  sourcePage?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  excerpt?: T;
  cover?: T;
  body?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
      };
  slug?: T;
  category?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "policies_select".
 */
export interface PoliciesSelect<T extends boolean = true> {
  title?: T;
  summary?: T;
  body?: T;
  slug?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stores_select".
 */
export interface StoresSelect<T extends boolean = true> {
  name?: T;
  province?: T;
  phone?: T;
  address?: T;
  mapUrl?: T;
  image?: T;
  openedAt?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "certifications_select".
 */
export interface CertificationsSelect<T extends boolean = true> {
  standard?: T;
  name?: T;
  number?: T;
  issuer?: T;
  holder?: T;
  decision?: T;
  scope?: T;
  location?: T;
  issuedAt?: T;
  expiresAt?: T;
  surveillance?: T;
  documents?:
    | T
    | {
        title?: T;
        image?: T;
        id?: T;
      };
  active?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  prefix?: T;
  _objectKey?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Thông tin công ty, hotline, mạng xã hội, menu — dùng trên toàn website.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  /**
   * Hiện trên website dạng "50+" / "hơn 50 cơ sở" (trang chủ, nhượng quyền, hệ thống cơ sở…). Nhập số tròn, vd 50, 100, 200.
   */
  storeCount?: number | null;
  legalName: string;
  brand: string;
  positioning?: string | null;
  slogan?: string | null;
  tagline?: string | null;
  taxCode?: string | null;
  email?: string | null;
  address?: string | null;
  geo?: {
    lat?: number | null;
    lng?: number | null;
  };
  hotlines?:
    | {
        number: string;
        display: string;
        contact?: string | null;
        id?: string | null;
      }[]
    | null;
  facebook?: {
    label?: string | null;
    url?: string | null;
  };
  tiktok?: {
    label?: string | null;
    url?: string | null;
  };
  zalo?:
    | {
        label?: string | null;
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  nav?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  primaryCta?: {
    label?: string | null;
    href?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  storeCount?: T;
  legalName?: T;
  brand?: T;
  positioning?: T;
  slogan?: T;
  tagline?: T;
  taxCode?: T;
  email?: T;
  address?: T;
  geo?:
    | T
    | {
        lat?: T;
        lng?: T;
      };
  hotlines?:
    | T
    | {
        number?: T;
        display?: T;
        contact?: T;
        id?: T;
      };
  facebook?:
    | T
    | {
        label?: T;
        url?: T;
      };
  tiktok?:
    | T
    | {
        label?: T;
        url?: T;
      };
  zalo?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  nav?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  primaryCta?:
    | T
    | {
        label?: T;
        href?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}